### ISSUE TITLE
Version 4.0 ROADMAP

### ISSUE THREAD

**Issue by janpecha** [Tharos/LeanMapper#155]
* [x] <del>PhpStan</del>
* [x] <del>typehints in methods parameters</del>
* [x] <del>`IRowMapper` - support for values conversion in `LeanMapper\Row` (value objects without `m:passThru`)</del>
* [x] stricter `$entity->set()` (no type conversions)
* [x] some small improvements and changes
* [x] PHP8
* [x] refactoring

**Comment by f3l1x** [comment]
Hi. How is it going with v4? :-)

**Comment by janpecha** [comment]
Hi, estimate for v4 is end of November, I hope it will go well, so keep fingers crossed :)

I created branch-alias, try it :)
